sprint 9
SvyatoslavLyskov/java-filmorate pull request #2
Opened 2023-04-14 20:05 UTC by SvyatoslavLyskov

1st iteration

2023-04-15 08:00 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к вашей работе.

2023-04-15 08:00 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (films.containsKey(film.getId())) {
Давайте валидационные проверки в отдельный приватный метод вынесем

2023-04-15 08:00 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else if (film.getName() == null || film.getName().isBlank()) {
Смотрите, можно воспользоваться библиотекой apache common 3 - StringUtils.isBlank(..), что позволит объединить эти 2 проверки. Кроме того, там есть еще довольно много полезных, удобных методов

2023-04-15 08:00 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (users.containsKey(user.getId())) {
Аналогично

2023-04-15 08:00 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(HttpStatus httpStatus, String s) {
Зачем сюда статус передаете?) Он же не используется. Кроме того, на факультатив вам https://struchkov.dev/blog/ru/exception-handling-controlleradvice/

2023-04-15 08:00 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Лишний пропуск

2023-04-15 08:00 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
Лишний пропуск

2023-04-15 08:00 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return film.getReleaseDate().isAfter(EPOCH_FILMS);
У Вас в Дтошке не проверяется, что дата заполнена, проверьте что она не null

2023-04-15 08:00 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        assertThrows(ValidationException.class, () -> controller.createFilm(film));
Еще можно проверить конкретное исключение, какая ошибка пришла, чтоб быть уверенным что сработала именно эта проверка

2023-04-15 08:00 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserController controller = new UserController();
Модификатор

2023-04-15 10:48 UTC, SvyatoslavLyskov commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(HttpStatus httpStatus, String s) {
вот,а я голову ломал,почему я пытаюсь везде передать статус,а он не используется)))

2023-04-16 06:53 UTC, Frilock approved these changes
Принял

2023-04-16 06:53 UTC, Frilock commented on pom.xml
> +			<version>3.12.0</version>
Версии библиотек правильнее в пропертиес выносить

2023-04-16 14:18 UTC, merged