sprint11,iter1
SvyatoslavLyskov/java-filmorate pull request #4
Opened 2023-05-24 14:06 UTC by SvyatoslavLyskov

2023-05-24 19:51 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе, жду новую версию.

2023-05-24 19:51 UTC, Frilock commented on pom.xml
> +			<version>2.0.0</version>
Версию лучше вынести в properties

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequiredArgsConstructor(onConstructor_ = {@Autowired})
А зачем onConstructor_ = {@Autowired}? Должно и без работать

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @GetMapping()
Пустые скобки не нужны

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +@Slf4j
Аннотация есть, а лога нет

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +@Slf4j
Аналогично, в других местах не пишу

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.getMutualFriends(userService.getUserById(id), userService.getUserById(otherId));
Логику поиска нужно перенести в сервис, передайте туда оба идентификатора и ищите уже там

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private LinkedHashSet<Genre> genres;
В сигнатуре метода правильнее в значении писать интерфейс, то есть просто Set, а когда инициализируете уже указывать реализацию. Кроме того, логичнее инициализировать коллекцию сразу тут, чтобы избежать лишних проверок на null. Кроме того, а почему Linked? Вам важен порядок элементов? Если же нет, достаточно обычно HashSet

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate) {
а зачем 2 конструктора? Это странно

2023-05-24 19:51 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (film.getName() == null || film.getName().isEmpty()) {
Данную проверку можно заменить на StringUtils.isEmtry. Вообще в данной библиотеке от apache common довольно много полезных функций

2023-05-24 22:05 UTC, SvyatoslavLyskov commented on pom.xml
> +			<version>2.0.0</version>
гуглил-ненагуглил,как запихнуть версию корректно,если с apache и java мне ясно-понятно,то тут я не разобрался,я так понимаю,это какая-то конкретная реализация jdbctemplate и что прописать в тег я не нашел-.-

2023-05-25 20:37 UTC, Frilock requested changes
Добрый вечер, пара мелких комментариев

2023-05-25 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@RequiredArgsConstructor(onConstructor_ = {@Autowired})
Зачем вы полностью аннотацию убираете ?  Я имел ввиду, что должно работать и так @RequiredArgsConstructor

2023-05-25 20:37 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Genre> genres = new HashSet<>();
Часть полей с модификаторами, а часть нет, почему? Приведите к одному виду

2023-05-25 20:37 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +@RequiredArgsConstructor(onConstructor_ = {@Autowired})
По поводу комментария с версиями в пропертис:

Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${example-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

Если не получиться пишите мне в пачке

2023-05-26 20:18 UTC, Frilock approved these changes
Принято

2023-05-27 17:23 UTC, merged